
isPROD: false

# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    mongodb:
      port: 27017
      uri: mongodb://localhost/test
      database: test
api:
  organization: /api/organization
  createOrganization: /api/createOrganization
  auth: /api/auth
  inventory: /api/inventory
  liveInventory:
    recipes: /api/liveInventory/stages
    plants: /api/liveInventory/plants
    plots: /api/liveInventory/plots
    shifts: /api/liveInventory/shifts
    stages: /api/liveInventory/stages
  users: /api/users
  usersSiteAdmin: /api/usersSiteAdmin
  admin:
    deleteOrganization: /api/admin/deleteOrganization


jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400000
  route:
    authentication:
      refresh: refresh

authentication:
  user: admin
  password: admin
  firstName: admin
  lastName: admin
  email: admin@admin.com
createNewUser:
  user: signUp
  password: signUp
  firstName: signUp
  lastName: signUp
  email: admin@admin.com

logging:
  level:
    org.springframework:
      security: DEBUG